type Email{
    emailAddress:String
    message:String
}

input EmailInput{
    emailAddress:String
    message:String
}

type Query {
    listEmail:[Email]
}

type Mutation {
    sendEmail(email:EmailInput):
}