/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "Auth": {
        "region": "us-east-1",
        "userPoolId": "us-east-1_yVK1jtnYy",
        "userPoolWebClientId": "3rcprpu8p5ro098ccgtan68e4r"
    }
};
export default awsmobile;